CREATE table espn_pitching (
player_id VARCHAR(10),
espn_id INT(10),
player_name VARCHAR(25),
team VARCHAR(3),
games_played INT(4),
games_started INT(4),
innings_pitched FLOAT(5),
hits INT(4),
runs INT(4),
earned_runs INT(4),
walks INT(4),
strikeouts INT(4),
wins INT(4),
losses INT(4),
saves INT(4),
holds INT(4),
blown_saves INT(4),
wins_above_replacement FLOAT(5),
walks_and_hits_per_innings_pitched FLOAT(5),
earned_run_average FLOAT(5),
complete_games INT(4),
shutouts INT(4),
total_batters_faced INT(4),
games_finished INT(4),
save_opportunities INT(4),
sacrifice_bunts INT(4),
sacrifice_flies INT(4),
hit_by_pitch INT(4),
grounded_into_double_plays INT(4),
wild_pitches INT(4),
balks INT(4),
quality_starts INT(4),
quailty_starts_percentage FLOAT(5),
strikeout_to_walk_ratio FLOAT(5),
strikeouts_per_nine_innings FLOAT(5),
number_of_pitches INT(4),
pitches_per_plate_appearance FLOAT(5),
pitches_per_inning FLOAT(5),
winning_percentage FLOAT(5),
average_game_score FLOAT(5),
ground_balls INT(4),
fly_balls INT(4),
ground_ball_to_fly_ball_ratio FLOAT(5),
run_support_average_per_start FLOAT(5),
component_era FLOAT(5),
component_era_ratio FLOAT(5),
defense_independent_era FLOAT(5),
defense_independent_era_ratio FLOAT(5),
tough_losses INT(4),
cheap_wins INT(4),
power_finesse_ratio FLOAT(5),
batting_average_on_balls_in_play FLOAT(5),
opponent_total_bases INT(4),
doubles INT(4),
triples INT(4),
home_runs INT(4),
runs_batted_in INT(4),
intentional_walks INT(4),
stolen_bases INT(4),
caught_stealing INT(4),
caught_stealing_percentage FLOAT(5),
opponents_batting_average FLOAT(5),
opponents_on_base_percentage FLOAT(5),
opponents_slugging_average FLOAT(5),
ops FLOAT(5),
season INT(4),
split VARCHAR(25),
ts DATETIME,
ds DATE
)
PARTITION BY LIST COLUMNS(season, split) (
PARTITION P2014Total VALUES IN ((2014,'Total')),
PARTITION P2014Home VALUES IN ((2014,'Home')),
PARTITION P2014Away VALUES IN ((2014,'Away')),
PARTITION P2014VsLeft VALUES IN ((2014,'VsLeft')),
PARTITION P2014VsRight VALUES IN ((2014,'VsRight')),
PARTITION P2014NoneOn VALUES IN ((2014,'NoneOn')),
PARTITION P2014RunnersOn VALUES IN ((2014,'RunnersOn')),
PARTITION P2014ScoringPos VALUES IN ((2014,'ScoringPos')),
PARTITION P2014ScoringPos2Out VALUES IN ((2014,'ScoringPos2Out')),
PARTITION P2014BasesLoaded VALUES IN ((2014,'BasesLoaded')),
PARTITION P2015Total VALUES IN ((2015,'Total')),
PARTITION P2015Home VALUES IN ((2015,'Home')),
PARTITION P2015Away VALUES IN ((2015,'Away')),
PARTITION P2015VsLeft VALUES IN ((2015,'VsLeft')),
PARTITION P2015VsRight VALUES IN ((2015,'VsRight')),
PARTITION P2015NoneOn VALUES IN ((2015,'NoneOn')),
PARTITION P2015RunnersOn VALUES IN ((2015,'RunnersOn')),
PARTITION P2015ScoringPos VALUES IN ((2015,'ScoringPos')),
PARTITION P2015ScoringPos2Out VALUES IN ((2015,'ScoringPos2Out')),
PARTITION P2015BasesLoaded VALUES IN ((2015,'BasesLoaded')),
PARTITION P2016Total VALUES IN ((2016,'Total')),
PARTITION P2016Home VALUES IN ((2016,'Home')),
PARTITION P2016Away VALUES IN ((2016,'Away')),
PARTITION P2016VsLeft VALUES IN ((2016,'VsLeft')),
PARTITION P2016VsRight VALUES IN ((2016,'VsRight')),
PARTITION P2016NoneOn VALUES IN ((2016,'NoneOn')),
PARTITION P2016RunnersOn VALUES IN ((2016,'RunnersOn')),
PARTITION P2016ScoringPos VALUES IN ((2016,'ScoringPos')),
PARTITION P2016ScoringPos2Out VALUES IN ((2016,'ScoringPos2Out')),
PARTITION P2016BasesLoaded VALUES IN ((2016,'BasesLoaded'))
);
